[[redirects]]
  from = "/api/*"
  to = "http://dbd-api-server-env.eba-vfmpfbem.ap-northeast-2.elasticbeanstalk.com/api/:splat"
  status = 200
  force = true
  headers = { "Cache-Control" = "no-cache" }